version: '3'

services:
  tracktor:
    build:
      dockerfile: ./Dockerfile
      context: ""
    container_name: tracktor
    depends_on:
      - database
    networks:
      - backend
    ports:
      - 80:80
    environment:
      - DATABASE_URL=mysql+asyncmy:///tracktor:tracktor@database:3306/tracktor
#      - DATABASE_URL=postgresql+asyncpg:///tracktor:tracktor@database:5432/tracktor

  database:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=tracktor
      - MYSQL_PASSWORD=tracktor
      - MYSQL_DATABASE=tracktor
    networks:
      - backend

#  EXAMPLE FOR POSTGRES
#  database:
#    container_name: codimd_db
#    image: postgres:14.0-alpine
#    environment:
#      - POSTGRES_USER=tracktor
#      - POSTGRES_PASSWORD=tracktor
#      - POSTGRES_DB=tracktor
#    networks:
#      - backend

networks:
  backend: