name: OpenAPI generation

#on:
#  push:
#    branches: [ master ]

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate openapi.json
        run:  python -c "import tracktor;import json;f = open('openapi.json','w');json.dump(tracktor.app.openapi(),f);f.close()"
      - name: Archive openapi.json
        uses: actions/upload-artifact@v2
        with:
          name: openapi.json
          path: openapi.json